# Generated by Django 3.0.4 on 2020-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_airport', models.CharField(max_length=100)),
                ('flight_type', models.CharField(max_length=10)),
                ('flight', models.CharField(max_length=30)),
                ('dest_airport', models.CharField(max_length=100)),
                ('plane', models.CharField(max_length=100)),
                ('plan_time', models.CharField(max_length=20)),
                ('fact_time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
